name: clay_containers
description: Easily create custom neumorphic container widgets for your own unique design.
version: 0.2.3
homepage: https://github.com/mcaubrey/clay_containers

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: